# -*- coding: utf-8 -*-
"""svm, sensivity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdsyiTy35JiEfxJzWQQvxBoPtCXW85j8
"""

svm_model = SVC(class_weight='balanced',probability=True)

# Specify the parameter grid for grid search
param_grid = {'C': [0.01,0.1, 1, 10, 100,1000], 'kernel': [ 'rbf','linear']}

# Perform grid search to find the best regularization parameter and kernel
grid_search = GridSearchCV(svm_model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best regularization parameter and kernel
best_c = grid_search.best_params_['C']
best_kernel = grid_search.best_params_['kernel']

# Train the SVM model with the best parameters
best_svm_model = SVC(C=best_c, kernel=best_kernel, class_weight='balanced',probability=True)
best_svm_model.fit(X_train, y_train)

a = []
for t in np.linspace(0,1):
  y_pred = (best_svm_model.predict_proba(X_val)[:,1] >= t).astype(bool) 
  confusion_matrix = metrics.confusion_matrix(y_val, y_pred)
  lr_auc = roc_auc_score(y_val, y_pred)
  a.append(round(lr_auc,4) )
  print(t, confusion_matrix , 'AUC' , round(lr_auc,4) , accuracy_score(y_val, y_pred))

print(max(a))

sensitivity = confusion_matrix[0, 0] / (confusion_matrix[0, 0] + confusion_matrix[1, 0])

# calculate the specificity
specificity = confusion_matrix[1, 1] / (confusion_matrix[1, 1] + confusion_matrix[0, 1])

# print the results
print('Sensitivity:', sensitivity)
print('Specificity:', specificity)

"""If you are predicting deaths, the most important metric to consider would be the sensitivity or recall, i.e., the ability of the model to correctly identify the true positive cases (i.e., actual deaths) out of all the positive cases (i.e., all the cases predicted as deaths).

The reason why sensitivity is more important in this case is that it's crucial to correctly identify all the actual deaths, even if it means that some non-death cases are incorrectly classified as deaths (resulting in lower specificity). For example, in the case of a medical diagnosis, failing to identify an actual death could have severe consequences, while a false positive (predicting death when the patient is actually alive) may have less severe consequences.
"""